doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
  orm:
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      AppModule:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Module'
        prefix: 'App\Module'
        alias: Module
