framework:
    rate_limiter:
        public_servers:
            policy: 'fixed_window'
            limit: 60
            interval: '1 minute'
        public_status:
            policy: 'fixed_window'
            limit: 60
            interval: '1 minute'
        public_downloads:
            policy: 'fixed_window'
            limit: 60
            interval: '1 minute'
        public_changelog:
            policy: 'fixed_window'
            limit: 60
            interval: '1 minute'
        public_docs:
            policy: 'fixed_window'
            limit: 60
            interval: '1 minute'
        public_registration:
            policy: 'fixed_window'
            limit: 10
            interval: '15 minutes'
        agent_bootstrap:
            policy: 'fixed_window'
            limit: 10
            interval: '5 minutes'
        instance_files_uploads:
            policy: 'fixed_window'
            limit: 30
            interval: '1 minute'
        instance_files_commands:
            policy: 'fixed_window'
            limit: 120
            interval: '1 minute'
