security:
  password_hashers:
    App\Module\Core\Domain\Entity\User: 'auto'

  providers:
    app_users:
      entity:
        class: App\Module\Core\Domain\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_users

  access_control: []
